service: angel
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  lambdaHashingVersion: 20201221
  stage: dev
  apiGateway:
    shouldStartNameWithService: true
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}*'
functions:
  angel:
    handler: api/api.angel
    environment:
      tableName: ${self:provider.environment.DYNAMODB_TABLE}-status
    events:
      - http:
          path: angel
          method: post
  getAll:
    handler: api/db/db.getAll
    environment:
      tableName: ${self:provider.environment.DYNAMODB_TABLE}-status
  get:
    handler: api/db/db.get
    environment:
      tableName: ${self:provider.environment.DYNAMODB_TABLE}-status
  put:
    handler: api/db/db.put
    environment:
      tableName: ${self:provider.environment.DYNAMODB_TABLE}-status
  update:
    handler: api/db/db.update
    environment:
      tableName: ${self:provider.environment.DYNAMODB_TABLE}-status
# DynamoDBの設定
resources:
  Resources:
    Angel:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}-status
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
plugins:
  - serverless-offline
  - serverless-dynamodb-local
custom:
  serverless-offline:
    httpPort: 8083
  dynamodb:
    stages: dev
    start:
      port: 8082
      inMemory: true
      migrate: true
      seed: true
    seed:
      angel:
        sources:
          - table: ${self:provider.environment.DYNAMODB_TABLE}-status
            sources: [./seeds/info.json]
